/smoother_server:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    action_server_result_timeout: 10.0
    autostart_node: false
    bond_heartbeat_period: 0.1
    costmap_topic: global_costmap/costmap_raw
    footprint_topic: global_costmap/published_footprint
    robot_base_frame: base_link
    smoother_plugins:
    - simple_smoother
    start_type_description_service: true
    transform_tolerance: 0.1
    use_sim_time: false

