/velocity_smoother:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    autostart_node: false
    bond_heartbeat_period: 0.1
    deadband_velocity:
    - 0.0
    - 0.0
    - 0.0
    enable_stamped_cmd_vel: false
    feedback: OPEN_LOOP
    max_accel:
    - 2.5
    - 0.0
    - 3.2
    max_decel:
    - -2.5
    - 0.0
    - -3.2
    max_velocity:
    - 0.25
    - 0.0
    - 1.5
    min_velocity:
    - -0.25
    - 0.0
    - -1.5
    odom_duration: 0.1
    odom_topic: odom
    scale_velocities: false
    smoothing_frequency: 20.0
    stamp_smoothed_velocity_with_smoothing_time: false
    start_type_description_service: true
    use_realtime_priority: false
    use_sim_time: false
    velocity_timeout: 1.0

