#!/usr/bin/env python3
"""fleet_arena.sdf 와 같은 형상의 AMCL 맵(pgm + yaml)을 만든다.

SLAM 을 돌리지 않고 월드에서 바로 맵을 뽑는다. 월드와 맵이 어긋나면 AMCL 이
수렴하지 않거나 엉뚱한 곳에 수렴하는데, 손으로 맞추면 반드시 어긋난다.

    python3 pinky_fleet_sim/scripts/make_arena_map.py

의존성은 표준 라이브러리뿐이다 (ROS 도 numpy 도 필요 없다).

월드를 고쳤으면 아래 WALLS 도 같이 고치고 이 스크립트를 다시 돌려야 한다.
"""

import os
from xml.etree import ElementTree

RESOLUTION = 0.05          # m/px. nav2_params_fleet.yaml 의 costmap 해상도와 맞춘다.

# 맵이 덮는 월드 범위. 아레나(1.5 x 2.5) 바깥으로 25cm 씩 여유를 둔다.
X_MIN, X_MAX = -1.0, 1.0
Y_MIN, Y_MAX = -1.5, 1.5

# ground_plane 은 벽이 아니다. 그 외 박스 모델을 전부 벽으로 본다.
SKIP_MODELS = {'ground_plane'}

FREE = 254                 # 흰색 = 주행 가능
OCCUPIED = 0               # 검정 = 벽

HERE = os.path.dirname(os.path.abspath(__file__))
SIM_PKG = os.path.dirname(HERE)
MAP_DIR = os.path.join(SIM_PKG, 'map')
NAME = 'fleet_arena'
WORLD = os.path.join(SIM_PKG, 'worlds', f'{NAME}.sdf')


def read_walls(path=WORLD):
    """월드 SDF 에서 벽 박스를 읽는다.

    벽 목록을 이 스크립트에도 적어 두었더니, 월드만 고치고 여기를 안 고쳐도 아무도
    모르는 상태가 됐다 (테스트조차 못 잡았다). 월드 파일 하나만 진실로 둔다.

    돌려주는 것: [(이름, 중심x, 중심y, 크기x, 크기y), ...]
    """
    tree = ElementTree.parse(path)
    walls = []
    for model in tree.getroot().iter('model'):
        name = model.get('name')
        if name in SKIP_MODELS:
            continue
        pose = model.find('pose')
        box = model.find('.//collision/geometry/box/size')
        if pose is None or box is None:
            continue
        px, py = (float(v) for v in pose.text.split()[:2])
        sx, sy = (float(v) for v in box.text.split()[:2])
        walls.append((name, px, py, sx, sy))
    if not walls:
        raise SystemExit(f'{path} 에서 벽을 하나도 못 찾았다')
    return walls


def cell_center(cx, cy, height):
    """셀 (cx, cy) 의 중심 월드 좌표.

    map_server 규약: origin 은 이미지 **좌하단**이고 월드 y 는 위로 갈수록 커지는데
    이미지 행 번호는 아래로 갈수록 커진다. 그래서 y 만 뒤집는다.
    """
    wx = X_MIN + (cx + 0.5) * RESOLUTION
    wy = Y_MIN + (height - 1 - cy + 0.5) * RESOLUTION
    return wx, wy


def build():
    """셀마다 중심이 벽 사각형 안에 드는지 검사한다.

    처음엔 벽의 양 끝을 픽셀로 변환해 그 사이를 칠했는데, 벽 두께 2cm 가 셀 5cm
    보다 얇아서 양 끝이 같은 픽셀로 반올림돼 벽이 통째로 사라졌다. 셀 단위로
    포함 여부를 보면 그런 경계 문제가 없다.
    """
    width = int(round((X_MAX - X_MIN) / RESOLUTION))
    height = int(round((Y_MAX - Y_MIN) / RESOLUTION))
    grid = [[FREE] * width for _ in range(height)]

    # 셀보다 얇은 벽도 최소 한 줄은 차지하게 한다. 실기 맵을 SLAM 으로 떠도
    # 얇은 벽은 이렇게 한 셀로 나온다.
    # 경계가 셀 중심과 정확히 겹칠 때 부동소수점 오차로 한쪽만 칠해지는 일이
    # 있었다 (서쪽 벽만 사라졌다). 셀의 1/1000 만큼 여유를 준다.
    eps = RESOLUTION * 1e-3
    boxes = []
    for _, cx, cy, sx, sy in read_walls():
        boxes.append((cx, cy,
                      max(sx, RESOLUTION) / 2.0 + eps,
                      max(sy, RESOLUTION) / 2.0 + eps))

    for py in range(height):
        for px in range(width):
            wx, wy = cell_center(px, py, height)
            for bx, by, hx, hy in boxes:
                if abs(wx - bx) <= hx and abs(wy - by) <= hy:
                    grid[py][px] = OCCUPIED
                    break
    return grid, width, height


def write_pgm(grid, width, height, path):
    with open(path, 'wb') as handle:
        # PGM 헤더는 ASCII 여야 한다 (주석도 마찬가지).
        handle.write(f'P5\n# generated by make_arena_map.py from fleet_arena.sdf\n'
                     f'{width} {height}\n255\n'.encode('ascii'))
        for row in grid:
            handle.write(bytes(row))


def write_yaml(path):
    with open(path, 'w', encoding='utf-8') as handle:
        handle.write(
            f'# fleet_arena.sdf 에서 생성됨 (make_arena_map.py). 손으로 고치지 말 것.\n'
            f'image: {NAME}.pgm\n'
            f'mode: trinary\n'
            f'resolution: {RESOLUTION}\n'
            f'origin: [{X_MIN}, {Y_MIN}, 0.0]\n'
            f'negate: 0\n'
            f'occupied_thresh: 0.65\n'
            f'free_thresh: 0.25\n')


def main():
    os.makedirs(MAP_DIR, exist_ok=True)
    grid, width, height = build()
    write_pgm(grid, width, height, os.path.join(MAP_DIR, f'{NAME}.pgm'))
    write_yaml(os.path.join(MAP_DIR, f'{NAME}.yaml'))
    occupied = sum(row.count(OCCUPIED) for row in grid)
    print(f'{NAME}: {width}x{height} px, {RESOLUTION} m/px, '
          f'origin [{X_MIN}, {Y_MIN}], 벽 {len(read_walls())}개 / '
          f'벽 셀 {occupied}개 -> {MAP_DIR}')


if __name__ == '__main__':
    main()
